### ISSUE TITLE
CS4ZP6 Tester Feedback: There is no signup.

### ISSUE THREAD

**Issue by Behzadkha** [trevorNgo/Measure2.0#145]
You can login with any text without signing up. 

**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
There is no button to sign-up. 
The email address filed does not check if it is valid email or not (you can login with email: 'tester' (it should make sure that at least there is an @ sign in it)).

**Expected result**
A sign up button to let people signup. 
Get an error message if I enter "tester" as my email address.
*Actual result*
No error message.
**Screenshot**
![image](https://user-images.githubusercontent.com/24414425/109193657-9bd92180-7766-11eb-958a-c052de1c94b2.png)

**Severity**
MEDIUM

**Comment by trevorNgo** [comment]
By design.

**Comment by Behzadkha** [comment]
How are the users going to be added?

**Comment by trevorNgo** [comment]
by an admin.
