### ISSUE TITLE
CS4ZP6 Tester Feedback: Redirection bug

### ISSUE THREAD

**Issue by Behzadkha** [trevorNgo/Measure2.0#146]
After closing the view plot. You will be navigated to the Input measurement tab not the original dashboard

Environment:
Windows Desktop,
Browser: Chrome

Steps to reproduce:
Login as instructor, 
Click on VIEW PLOTS
Close the plot and you will be redirected to the INPUT MEASUREMENT tab instead of the main dashboard
![image](https://user-images.githubusercontent.com/24414425/109177497-df775f80-7755-11eb-91ce-6c73af7fec7a.png)

Severity:
LOW

**Comment by trevorNgo** [comment]
@michaelkhancode this may be by design now, so we may want to remove this button shortcut.

**Comment by michaelkhancode** [comment]
I think removing the button makes the most logical sense.

**Comment by michaelkhancode** [comment]
resolved in: https://github.com/trevorNgo/Measure2.0/pull/246
