### ISSUE TITLE
CS4ZP6 Tester Feedback: Can not mark only one LEARNING OUTCOME as complete.

### ISSUE THREAD

**Issue by Behzadkha** [trevorNgo/Measure2.0#153]
By clicking on the "Mark as Complete" all the "learning outcomes" will be locked. There isn't a way to only mark one of the learning outcomes.

**Environment**
Windows desktop,
Browser: Chrome

**Steps to reproduce**
Login as INSTRUCTOR
click on INPUT MEASUREMENT.
There is no option to select one learning outcome and mark it as complete.

**Expected result**
Be able to select a "learning outcome" and then mark it as complete.
**Actual result**
Mark as complete locks all of the learning outcomes.
**Screenshot**
![image](https://user-images.githubusercontent.com/24414425/109185975-7f38eb80-775e-11eb-93f6-7777c1f49974.png)

**Severity**
MEDIUM

**Comment by trevorNgo** [comment]
Intentional design decision by requirements.
