### ISSUE TITLE
CS4ZP6 Tester Feedback: change your password error

### ISSUE THREAD

**Issue by darrentu** [trevorNgo/Measure2.0#157]
<img width="445" alt="Screen Shot 2021-02-25 at 12 55 35 PM" src="https://user-images.githubusercontent.com/12387761/109195842-025f3f00-7769-11eb-84d3-2a85f372bf0a.png">
Describe the feedback/issue.

Please list the reproduction steps
I entered in test@test.com as the username and 'test' as the password in the login. 
https://measuredemo.azurewebsites.net/instructor

**Comment by trevorNgo** [comment]
this is a chrome password manager warning :)
