### ISSUE TITLE
Security bug: Authentication allowed over HTTP on website

### ISSUE THREAD

**Issue by bucklj4** [trevorNgo/Measure2.0#159]
- Severity: High

## Description
It is possible to access the site http://measuredemo.azurewebsites.net/ over HTTP. Indeed, measuredemo.azurewebsites.net/ defaults to HTTP. It is then possible to enter authentication credentials, and continue forward in the application.

Authentication over HTTP (rather than HTTPS) should not be allowed because one cannot ensure the confidentiality or integrity of the user who is logging in.

### Steps to Reproduce
1. Navigate to http://measuredemo.azurewebsites.net/
2. Enter `user@email.com` (or any email) in the email field.
3. Enter `secret` (or any password) in the password field.
4. Click `Sign in Instructor`.

### Actual Result
Login was successful over HTTP.

### Expected Result
User should have been redirected to an HTTPS page over which to log in, or log in should be refused over HTTP.

### Attachments
<img width="1796" alt="Screenshot 2021-02-25 at 9 10 17 PM" src="https://user-images.githubusercontent.com/35265275/109245196-0b263400-77ae-11eb-904a-c1a8bfbef4ea.png">
<img width="1796" alt="Screenshot 2021-02-25 at 9 10 30 PM" src="https://user-images.githubusercontent.com/35265275/109245229-1a0ce680-77ae-11eb-83f8-bd2962ae03e0.png">

### Contact
bucklj4@mcmaster.ca

**Comment by trevorNgo** [comment]
Few things, I deployed the app temporarily for your testing convenience. I have now changed the setting on the service so access over HTTP is now forbidden. Good catch.

As well, the app is intended to be integrated with MacAuth in the future, so as far as auth via Identity provider goes, it will be as secure as McMaster + UTS can guarantee it to be.

The app also will be only accessible on campus network, and the server is actually already HTTPS-ready, it simply requires the valid TLS certificate from UTS that Mac uses.

We have provided this sign in page as a temporary landing page with the intention of being removed in the future.
