### ISSUE TITLE
CS4ZP6 Tester Feedback: Refreshing the Curriculum Map page removes most page elements 

### ISSUE THREAD

**Issue by bucklj4** [trevorNgo/Measure2.0#163]
- Severity: Low

## Description
On the Curriculum Map page, refreshing the browser window destroys most page elements.

### Steps to Reproduce
1. Login as department coordinator.
2. Select `Curriculum Map`.
3. Click refresh in the browser window.

### Actual result
The Curriculum Map is reloaded with the same elements it had before.

### Expected result
All elements on the page save for the `Curriculum Map` header text are removed.

#### Before refresh
<img width="1864" alt="Screenshot 2021-02-25 at 10 46 04 PM" src="https://user-images.githubusercontent.com/35265275/109252349-5135c480-77bb-11eb-8f48-aee0cf13b36b.png">

#### After refresh
<img width="1864" alt="Screenshot 2021-02-25 at 10 47 00 PM" src="https://user-images.githubusercontent.com/35265275/109252373-627ed100-77bb-11eb-9d9a-18879f297ae1.png">

**Comment by trevorNgo** [comment]
you have to be "signed in" to access such page... So this is a win.
