### ISSUE TITLE
CS4ZP6 Tester Feedback: Refreshing clears sidebar

### ISSUE THREAD

**Issue by coffeexcode** [trevorNgo/Measure2.0#170]
### Severity
High

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Log in to the department coordinator account
2. From the main page, hit the browser refresh button
3. Inspect the sidebar

### Expected:
The sidebar should have the 3 links

### Actual:
The sidebar has no more links

#### Before Refresh
![image](https://user-images.githubusercontent.com/13461008/109365830-0ae67100-7860-11eb-96f5-9a63def0c2d2.png)

#### After
![image](https://user-images.githubusercontent.com/13461008/109365872-1b96e700-7860-11eb-8efe-1dcd014c1cfa.png)

**Comment by trevorNgo** [comment]
Duplicate Issue: https://github.com/trevorNgo/Measure2.0/issues/164
