### ISSUE TITLE
CS4ZP6 Tester Feedback: Possibly Missing Page Elements in "Input Measurement"

### ISSUE THREAD

**Issue by coffeexcode** [trevorNgo/Measure2.0#171]
### Severity
High

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Log in as instructor
2. Click on Eng Phys 4pp3 "Input Measurement" button

### Expected:
There should be something to input

### Actual:
The page is mostly blank. The page suggest when I go back that I'm leaving unsaved changes despite doing nothing and no elements I could have changed

### Screenshot:
![image](https://user-images.githubusercontent.com/13461008/109366481-8a287480-7861-11eb-8dce-8a8e019b91f8.png)

**Comment by trevorNgo** [comment]
This must be because a department coordinator user can disable the lists of learning outcomes. You must have logged in when another tester disabled them all...

**Comment by trevorNgo** [comment]
Some of them are enabled again as of time of writing.
