### ISSUE TITLE
CS4ZP6 Tester Feedback: Reloading Hides SideBar Elements

### ISSUE THREAD

**Issue by SEsseltine** [trevorNgo/Measure2.0#172]
### Bug Description
Elements of the side navigation bar change after page reloads. More specifically, the Dashboard option is no longer available.

### Recreation Steps
Logged-in as an instructor:
1. Toggle the sidebar open
2. Refresh the page
3. Toggle the sidebar open

### Environment
**Browser:** Google Chrome

### Expected Behaviour
Sidebar links should persist after page reloads.

### Actual Behaviour 
Sidebar links are changed/removed after page reloads.

### Supporting Images
![Screen Shot 2021-02-26 at 5 27 49 PM](https://user-images.githubusercontent.com/16650214/109370817-ec887180-786f-11eb-9881-af8066b3fe5d.png)

**Comment by trevorNgo** [comment]
Duplicate Issue: https://github.com/trevorNgo/Measure2.0/issues/164
