### ISSUE TITLE
CS4ZP6 Tester Feedback: Adding New CEAB Attribute to Curriculum Map Gets No Description

### ISSUE THREAD

**Issue by SEsseltine** [trevorNgo/Measure2.0#175]
### Bug Description
When adding a new CEAB Attribute that currently is not represented in the hamburger menu, the classification title/description is not added to the hamburger menu.

**Severity:** LOW

### Recreation Steps
Logged-in as a Department Coordinator, from the Curriculum Map Page:
1. Click the Add Indicator button
2. Click to select a major classification category that is not yet represented in the list

### Environment
**Browser:** Google Chrome

### Expected Behaviour
The description of the classification should be added with the CEAB Attribute #

### Actual Behaviour 
Only the CEAB Attribute # is added

### Supporting Images
![Screen Shot 2021-02-26 at 9 28 19 PM](https://user-images.githubusercontent.com/16650214/109373008-7fc6a480-787a-11eb-8db2-d512376cbb73.png)
![Screen Shot 2021-02-26 at 9 33 56 PM](https://user-images.githubusercontent.com/16650214/109373009-805f3b00-787a-11eb-8fec-59c40b1d8cd9.png)

**Comment by michaelkhancode** [comment]
resolved
