### ISSUE TITLE
CS4ZP6 Tester Feedback: Wrong buttons highlighted in graphs

### ISSUE THREAD

**Issue by Gregory-Kitching** [trevorNgo/Measure2.0#181]
When viewing plots of a rubric form, the wrong buttons are highlighted. When viewing attributes, the "Attributes" button is darkened and the "Indicators" button is light. This is the opposite of what would be expected, the selected button should be brighter than non-selected buttons.

Steps to reproduce:
1. Log in as instructor
2. Click "View Plots"

![Screenshot from 2021-02-27 13-39-47](https://user-images.githubusercontent.com/79662360/109396809-4ab16500-7901-11eb-917f-f23aea375799.png)

![Screenshot from 2021-02-27 13-38-59](https://user-images.githubusercontent.com/79662360/109396810-4dac5580-7901-11eb-945e-15e1820ad1c1.png)

**Comment by trevorNgo** [comment]
I disagree, @Gregory-Kitching. Most design languages in light theme darken buttons on interaction and confirmation.

**Comment by trevorNgo** [comment]
Closing because team and project sponsor decided against.
