### ISSUE TITLE
CS4ZP6 Tester Feedback: No constraints on the type of file uploaded

### ISSUE THREAD

**Issue by Gregory-Kitching** [trevorNgo/Measure2.0#182]
Any kind of file can be uploaded to a rubric form, including music, programs, etc.

Steps to reproduce:
1. Log in as instructor
2. Go to "Input measurement"
3. Expand a learning outcome
4. Click upload  button
5. Upload any file smaller than 500kB
6. Click "Save"

![Screenshot from 2021-02-27 14-00-48](https://user-images.githubusercontent.com/79662360/109397400-5ce0d280-7904-11eb-94ea-926263c733cd.png)

![Screenshot from 2021-02-27 14-01-09](https://user-images.githubusercontent.com/79662360/109397401-5eaa9600-7904-11eb-933c-f34fe013463f.png)

![Screenshot from 2021-02-27 14-01-30](https://user-images.githubusercontent.com/79662360/109397403-60745980-7904-11eb-87cf-0f8b0a1585c5.png)

**Comment by trevorNgo** [comment]
this is expected behavior.
