### ISSUE TITLE
CS4ZP6 Tester Feedback: Rubric form link on main page disappears

### ISSUE THREAD

**Issue by Gregory-Kitching** [trevorNgo/Measure2.0#183]
Reloading the rubric form page then pressing back results in the rubric form link disappearing.

Steps to reproduce:
1. Log in as instructor
2. Click "Input Measurement"
3. Reload page
4. Click back
5. Click "Ok"

![Screenshot from 2021-02-27 14-12-18](https://user-images.githubusercontent.com/79662360/109397851-f610e880-7906-11eb-9c16-02d0fa383feb.png)
Before

![Screenshot from 2021-02-27 14-14-28](https://user-images.githubusercontent.com/79662360/109397856-fc9f6000-7906-11eb-849c-d03510dd743c.png)
After

**Comment by trevorNgo** [comment]
https://github.com/trevorNgo/Measure2.0/issues/159#issuecomment-786365994

User states is not saved in browser so reloading page naturally resets the app...

**Comment by trevorNgo** [comment]
Also, you have to be "signed in" to access data from this page... So this is actually a win.
