### ISSUE TITLE
CS4ZP6 Tester Feedback: [SECURITY ISSUE] Password is not secure

### ISSUE THREAD

**Issue by darrentu** [trevorNgo/Measure2.0#195]
I understand that this repository was not meant to be a public repo.

However, it currently is a public repo and the password is exposed out in the open. This is a serious security issue.

https://github.com/trevorNgo/Measure2.0/blob/e9ead2c5205aaca952cdb5342e1a6a7a3fc82b8b/sourcecode/server/.env#L3

Note - this review is for a school course

**Comment by trevorNgo** [comment]
db for testing
