### ISSUE TITLE
CS4ZP6 Tester Feedback: [SECURITY ISSUE] private key is exposed

### ISSUE THREAD

**Issue by darrentu** [trevorNgo/Measure2.0#197]
I understand that this repository was not meant to be a public repo.

However, it currently is a public repo and the private key is exposed out in the open. This is a serious security issue.

https://github.com/trevorNgo/Measure2.0/blob/main/sourcecode/server/cert/private.pem

Note - this review is for a school course

**Comment by trevorNgo** [comment]
thats a self-made insecure ssl cert for testing
