### ISSUE TITLE
CS4ZP6 Tester Feedback: [SEO issue] Missing keywords

### ISSUE THREAD

**Issue by darrentu** [trevorNgo/Measure2.0#198]
For search engine optimization, ensure that you contain keywords inside of your metadata within your react app. 

https://github.com/trevorNgo/Measure2.0/blob/e9ead2c5205aaca952cdb5342e1a6a7a3fc82b8b/sourcecode/frontend/public/index.html#L9

Without doing this, you will potentially violate guideline 1.8 Be Easily Found in the Top 30 (in the HCI guideline book). You want to ensure that your app can be found within the top 30 sites from a search engine. 

Guideline book URL: https://www.usability.gov/sites/default/files/documents/guidelines_book.pdf

Note - this review is for a school course

**Comment by trevorNgo** [comment]
Not a public domain, internal tool for McMaster only.
