### ISSUE TITLE
CS4ZP6 Tester Feedback: Rubric Form 

### ISSUE THREAD

**Issue by liangw27** [trevorNgo/Measure2.0#201]
Describe the feedback/issue.

When I tried to witness rubric form for ENG PHYS 4PP3, I found that the content of a row is overflowing. I think this problem is raised by css.

![1](https://user-images.githubusercontent.com/71243523/110142267-f29ec500-7e10-11eb-8107-92567dcb7b37.PNG)

**Comment by trevorNgo** [comment]
Duplicate issue: https://github.com/trevorNgo/Measure2.0/issues/189
