### ISSUE TITLE
CS4ZP6 Tester Feedback: Notification button

### ISSUE THREAD

**Issue by liangw27** [trevorNgo/Measure2.0#202]
Describe the feedback/issue.

When I tried to access message and click on the button at the right top side of the website, there is nothing showing up.
![2](https://user-images.githubusercontent.com/71243523/110143212-f4b55380-7e11-11eb-9b5e-37f84a12c75a.PNG)

**Comment by trevorNgo** [comment]
Duplicate Issue: https://github.com/trevorNgo/Measure2.0/issues/142
