### ISSUE TITLE
CS4ZP6 Tester Feedback: Can have two "Final Exam" learning outcomes for the same Category

### ISSUE THREAD

**Issue by elwazana** [trevorNgo/Measure2.0#212]
Enviroment
- Google Chrome
- Windows 10

Describe the feedback/issue.
You can create and save two learning outcomes listed as `Final Exams` for the same category:
![image](https://user-images.githubusercontent.com/35268928/110225989-ab6c0f00-7eb8-11eb-8b29-9399218be618.png)
![image](https://user-images.githubusercontent.com/35268928/110225991-b9219480-7eb8-11eb-8f4a-2a96406e740a.png)

Priority
LOW (not a requirement but would be nice to have a popup warning)

Please list the reproduction steps
- Login as `Department Coordinator && Instructor`
- Navigate to `Input Measurment`
- Create two different `Learning Outcomes` under the same category both with `Final Exam` labels

**Comment by trevorNgo** [comment]
this is allowed....
