### ISSUE TITLE
UI - "Any unsaved fields will be lost. Are you sure you want to leave?" message prompt on none input page

### ISSUE THREAD

**Issue by lix229** [trevorNgo/Measure2.0#214]
# Summary
"Any unsaved fields will be lost. Are you sure you want to leave?" message prompts on pages that have no input fields, i.e. VIEW PLOTS.

# Env
- macOS version: 11.2.2
- Chrome 
# Logs and Issue recreation
## Logs
N/A

## Issue recreation
1.  Login as instructor
2. Click `VIEW PLOTS` on dashboard
3. Go back to last page
4. Prompts `Any unsaved fields will be lost. Are you sure you want to leave?`.

![Screen Shot 2021-03-07 at 3 43 06 PM](https://user-images.githubusercontent.com/35265304/110254137-d22f5180-7f5b-11eb-9b3f-940cd902ce76.png)

**Comment by trevorNgo** [comment]
As per our requirements from our capstone advisor, View Plots is a modal that opens from the Input Measurement. I'm sorry you find this confusing.

**Comment by trevorNgo** [comment]
https://github.com/trevorNgo/Measure2.0/issues/215
