### ISSUE TITLE
UI - Inconsisitent behavior, go back always return to dashboard

### ISSUE THREAD

**Issue by lix229** [trevorNgo/Measure2.0#215]
# Summary
When logged in as instructor, if selected `VIEW PLOTS` within `INPUT MEASUREMENT`, go back will directly return to dashboard, while clicking `X` will go back to `INPUT MEASUREMENT`, this is a bit confusing and inconsistent.

# Env
- macOS version: 11.2.2
- Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)

# Logs and Issue recreation
## Logs
N/A
## Issue recreation
1. Log in as instructor
2. Enter `INPUT MEASUREMENT`
3. Click `VIEW PLOTS`
4. Go back // Goes to dashboard instead of `INPUT MEASUREMENT`

**Comment by trevorNgo** [comment]
As per our requirements from our capstone advisor, View Plots is a UI modal that opens from the Input Measurement. I'm sorry you find this confusing.
