### ISSUE TITLE
UI - Input fields locked

### ISSUE THREAD

**Issue by lix229** [trevorNgo/Measure2.0#216]
# Summary
When logged in as instructor, the input fields are always locked.

# Env
- macOS version: 11.2.2
- Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)

# Logs and Issue recreation
## Logs
N/A
## Issue recreation
1. Log in as instructor
2. Enter `INPUT MEASUREMENTS`
3. Expand any forms
![Screen Shot 2021-03-07 at 3 53 53 PM](https://user-images.githubusercontent.com/35265304/110254482-52a28200-7f5d-11eb-8ad1-cb2c30587e9e.png)

**Comment by trevorNgo** [comment]
![image](https://user-images.githubusercontent.com/23327878/110254762-7fa36480-7f5e-11eb-84f5-3e7841e29629.png)
