### ISSUE TITLE
Curriculum Map - Number of indicators allowed are limited

### ISSUE THREAD

**Issue by lix229** [trevorNgo/Measure2.0#217]
# Summary
The number of indicators allowed for a course has a ceiling, and the maximum number allowed is less then options presented.

# Env
- macOS version: 11.2.2
- Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)

# Logs and Issue recreation
## Logs
N/A
## Issue recreation
1. Log in as `DEPARTMENT COORDINATOR`
2. For any term, select `CURRICULUM MAP`.
3. Keep adding indicators.
4. The button will be disabled after a number of attempts.

![Screen Shot 2021-03-07 at 4 04 51 PM](https://user-images.githubusercontent.com/35265304/110254893-28ea5a80-7f5f-11eb-80e1-68059257e3e0.png)
![Screen Shot 2021-03-07 at 4 05 00 PM](https://user-images.githubusercontent.com/35265304/110254896-2a1b8780-7f5f-11eb-8632-a1015a6987f0.png)

**Comment by trevorNgo** [comment]
This is the correct behavior.

**Comment by lix229** [comment]
As you can see in the first screen shot, I did not select all the possible indicators, and this behavior varies between different courses.

For instance, PHYS 4PP3 allows you to add indicators until there are only 1 left.
![Screen Shot 2021-03-07 at 4 17 29 PM](https://user-images.githubusercontent.com/35265304/110255238-b7131080-7f60-11eb-983f-764dc2e12363.png)

But if I select any of the 2, it will not allow me to add the last one.
![Screen Shot 2021-03-07 at 4 18 27 PM](https://user-images.githubusercontent.com/35265304/110255242-c09c7880-7f60-11eb-8398-0ce5d230f19d.png)

**Comment by trevorNgo** [comment]
I see, it appears we have an off by one bug. @michaelkhancode

**Comment by michaelkhancode** [comment]
resolved in: https://github.com/trevorNgo/Measure2.0/pull/246
