### ISSUE TITLE
UI - Accessing inaccessable options as departmentcoordinator

### ISSUE THREAD

**Issue by lix229** [trevorNgo/Measure2.0#220]
# Summary
Can trick the system into treating the user as `department coordinator & instructor` when logged in only as `INSTRUCTOR`, this also breaks the side menu.

# Env
- macOS version: 11.2.2
- Google Chrome Version 88.0.4324.192 (Official Build) (x86_64)

# Logs and Issue recreation
## Logs
N/A
## Issue recreation
1. Log in as `DEPARTMENT COORDINATOR`
2. Log out
3. log in as INSTRUCTOR
4. Hit go back 
5. Now the URL suggests I am a department coordinator, but I have access to instructor options, and I never logged in as both, while the side menu seems to stay as one would see as an instructor.

![Screen Shot 2021-03-07 at 4 31 03 PM](https://user-images.githubusercontent.com/35265304/110255588-8338ea80-7f62-11eb-93f4-6ae6eab7dde5.png)

**Comment by michaelkhancode** [comment]
resolved in: https://github.com/trevorNgo/Measure2.0/pull/246
