### ISSUE TITLE
CS4ZP6 Tester Feedback: Program map level editor submit button accepts blank form

### ISSUE THREAD

**Issue by DavidHospital** [trevorNgo/Measure2.0#223]
## Description
When editing a level of a program in the Program Map, the "EditLevelModal" "Submit" button is clickable if both "Add Course" and "Remove Course" fields are blank. After clicking Submit, modal disappears.

## Steps to reproduce
- Sign in as Department Coordinator
- Navigate to Program Map
- Click on a Level to edit
- Keep the form blank
- Press "Submit" on the modal

## Attachments
![manage_program_submit_button](https://user-images.githubusercontent.com/19175976/110255880-09096580-7f64-11eb-9ab5-bb048629fef7.PNG)

**Comment by michaelkhancode** [comment]
resolved in: https://github.com/trevorNgo/Measure2.0/pull/246
