### ISSUE TITLE
CS4ZP6 Tester Feedback: Clicking View Past Reports under Graduate Attribute Report does not do anything

### ISSUE THREAD

**Issue by myrithok** [trevorNgo/Measure2.0#226]
**Description:** Clicking the **View Past Reports** button under the  **Graduate Attribute Report** on the homepage when logged in as an **Admin** does not do anything.

**OS:** Windows 10 Enterprise
**Browser:** Chrome Version 89.0.4389.82

**Reproduction steps:**

* Sign in as an **Admin**
* Click on **View Past Reports** under the **Graduate Attribute Report** section

**Expected result:**
Past reports should become visible.

**Actual result:**
Nothing happens when the button is clicked
![image](https://user-images.githubusercontent.com/32877366/110256114-25f26880-7f65-11eb-9e3c-1a03db34c9f7.png)

**Comment by trevorNgo** [comment]
Duplicate with your past issue: https://github.com/trevorNgo/Measure2.0/issues/224

**Comment by myrithok** [comment]
> Duplicate with your past issue: #224

I believe this issue was closed in error. Issue #224 refers to the Faculty Recommendations Report; this issue is regarding Graduate Attribute Reports.
