### ISSUE TITLE
CS4ZP6 Tester Feedback: Archive Year Term have wrong notification time 

### ISSUE THREAD

**Issue by caok10** [trevorNgo/Measure2.0#267]
Environment

Google Chrome
Windows 10

![sdsdsdsd](https://user-images.githubusercontent.com/48635106/110288190-9fb24280-7fb5-11eb-954b-4bce0a5c3d79.PNG)
The job finished time should be current time

Please list the reproduction steps
Login as Admin
Navigate to Archive Year Term to the end

**Comment by trevorNgo** [comment]
Duplicate: https://github.com/trevorNgo/Measure2.0/issues/259
